apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic

  name: petclinic
  namespace: petclinic

spec:

  replicas: 1

  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:

      labels:
        app: petclinic
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/vamsi-cloud/docker-repo/petclinic:${containerImageTag}
        imagePullPolicy: IfNotPresent
        name: petclinic

   
